Output demo.gif

Set FontSize 11
Set Width 1200
Set Height 600

Type "pg_walview /tmp/pgdata/pg_wal/000000010000000000000010"

Sleep 500ms

Enter
Sleep 2s

Down
Sleep 700ms

Down
Sleep 700ms

Down
Sleep 700ms

Down
Sleep 700ms

Down
Sleep 700ms

Down
Sleep 700ms

Down
Sleep 700ms

Down
Sleep 700ms

Down
Sleep 700ms

Tab
Sleep 700ms

Enter
Sleep 700ms

Enter
Sleep 700ms

Down
Sleep 700ms

Enter
Sleep 700ms

Tab
Sleep 700ms

Down 5
Sleep 700ms

Type "q"
Sleep 3s
